#!/bin/sh

main() {
(
        file="$1"; shift
	facility="$1"; shift
	SRC="$1"; shift

        if [ -z "$file" ]; then
                exec_cmd "$facility" "list"
                return $?
        fi
        if [ ! -f "$file" ]; then
                echo "No such file: $file"
                return 1
        fi
        cmake_file="$cmake_dir/${file/src/facility}.cmake"

	echo "Deleting: $file"

	rm -f "$cmake_file"
)
}

