#!/bin/sh

info_cmd="Initalizes project"

helper() {
(
	facility="$1"; shift
	cmd="$1"; shift

	. "$workload_dir/$facility/meta"
	exec_cmd "$facility" "$cmd" "$@"

)
}

main() {
(
	helper "controller" "create" "base"
	helper "controller" "create" "base"
)
}
