#!/bin/sh

info_cmd="Creates entity classes"

helper() {
(
	facility="$1"; shift
	cmd="$1"; shift

	. "$workload_dir/$facility/meta"
	exec_cmd "$facility" "$cmd" "$@"

)
}

main() {
(
	view_level="$1"; shift
	if [ -z "$view_level" ]; then
		echo "Please specify view level"
		return 1
	fi
	if ! printf "%04d" "$view_level" &>/dev/null; then
		echo "Invalid view level number: $view_level"
		return 1
	fi
	if [ "`printf "%04d\n" "$view_level"`" != "$view_level" ]; then
		view_level="`printf "%04d\n" "$view_level"`"
	fi

	helper "controller" "create" "$@"
	helper "model" "create" "$@"
	helper "html_view" "create" "$view_level" "$@"
)
}
