#!/bin/sh

info_cmd="Creates entity classes"

helper() {
(
	facility="$1"; shift
	cmd="$1"; shift

	. "$workload_dir/$facility/meta"
	exec_cmd "$facility" "$cmd" "$@"

)
}

main() {
(
	override=""
        if [ "$1" = "-f" ]; then
                override="-f"
                shift
        fi
	view_level="$1"; shift
	if [ -z "$view_level" ]; then
		echo "Please specify view level"
		return 1
	fi
	if ! printf "%04d" "$view_level" &>/dev/null; then
		echo "Invalid view level number: $view_level"
		return 1
	fi

	helper "controller" "create" $override "$@"
	helper "model" "create" $override "$@"
	helper "html_view" "create" $override "$view_level" "$@"
)
}
