#!/bin/sh

info_cmd="Creates mview"

main() {
(
	override="false"
	if [ "$1" = "-f" ]; then
		override="true"
		shift
	fi
	if [ ${#@} -lt 1 ]; then
		echo "Please specify skin name"
		return 1
	fi

	name="`echo "$@" | tr ' ' '_'`"
	include="`echo "$@" | tr ' ' '/'`"
	uses="`echo "$@" | sed 's/ /::/g'`"

	file="$src_dirs/`echo "$@" | tr ' ' '/'`.tmpl"

	if [ -e "$file" ] && [ "$override" != "true" ]; then
		echo "File '$file' already exists. Refusing to proceed."
		echo "Use -f to override."
		return 1
	fi


	mkdir -p `dirname "$file"`

cat <<EOF > "$file"
<% c++ #include "${include}.h" %>
<% skin html %>
<% view $name uses model::${uses} extends base %>

<% template body_content() %>
hello!
<% end template %>

<% end view %>
<% end skin %>
EOF
	exec_cmd "$facility" "add" "$file"
)
}
