#!/bin/sh

info_cmd="Dels file"

main() {
(
	file="$1"; shift

	if [ -z "$file" ]; then
		exec_cmd "$facility" "list"
		return $?
	fi
	
	if [ ! -f "$file" ]; then
		echo "No such file: $file"
		return 1
	fi
	
	cmake_file="`map "$file"`"

	echo "Deleting file: $file"
	
	rm -f "$cmake_file"
)
}
